### ISSUE TITLE
Chunked responses aren't being handled correctly for windows

### ISSUE THREAD

**Issue by jumpsplat120** [love2d/lua-https#19]
Attempting to get the data from `https://www.weatherapi.com/` returns a body of `{"location": [...snip],"time":"2023-06-26 0`, which is supposed to be valid JSON.

**Comment by MikuAuahDark** [comment]
Do you have another site example with chunked encoding? weatherapi API requires sign-up for access.

**Comment by jumpsplat120** [comment]
I've PM'd you the full link that I'm using, which includes my API key, which I'll regenerate after this is resolved.
