### ISSUE TITLE
Add artifact for Apple Silicon

### ISSUE THREAD

**Issue by ropoko** [love2d/lua-https#27]
The current mac-os artifact is only for x86_64, and it would be nice to have the arm64 version

**Comment by tpimh** [comment]
Definitely a good idea.

https://github.com/love2d/love/issues/2008#issuecomment-1902277707:

> According to https://store.steampowered.com/hwsurvey/Steam-Hardware-Software-Survey-Welcome-to-Steam?platform=mac 70% of mac steam users have an arm64 system, so you might not want to leave that out - and your x64 library will fail to work on those systems anyway unless you strip out the arm64 part of love.app to make it use Rosetta x64 emulation.

**Comment by slime73** [comment]
I want to do this, but I'd like it to be a fat binary containing both arm64 and x64 (just like love and other native apps and libraries), which probably needs a bit more fiddling with the CI setup and maybe the CMake project than otherwise.

**Comment by slime73** [comment]
Done in [221bb84](https://github.com/love2d/lua-https/commit/221bb8413a8bc86f7e0db878db6cd55fab682ce9)
