### ISSUE TITLE
REST capabilities

### ISSUE THREAD

**Issue by tpimh** [love2d/lua-https#28]
Only thing that is missing to implement REST is JSON encode/decode functions. It was recently discussed (and declined) here https://github.com/love2d/love/issues/1548.

Maybe this library would be the right place to also include JSON serialization and deserialization functions?

For example, LÖVR has its own implementation of http library, and also bundles CJSON.

**Comment by MikuAuahDark** [comment]
No. There are many JSON encode/decode in Lua, both pure Lua and C modules. Providing JSON encoding/decoding capabilities is out-of-scope of this library.
