### ISSUE TITLE
Android module "https" not found

### ISSUE THREAD

**Issue by lmfff** [love2d/lua-https#7]
Hi everyone!
I successfully compiled the https.dll and got example.lua to work under Windows 11
I tried compiling an .apk following the wiki instructions for Android compilation but I get this error when launching the apk on my Android device:

```
Error

main.lua:3: module 'https' not found:
no field package.preload['https']
no 'https' in LOVE game directories.
no file 'https' in LOVE paths.
no file './https.lua'
no file '/usr/local/share/luajit-2.1.0-beta3/https.lua'
no file '/usr/local/share/lua/5.1/https.lua'
no file '/usr/local/share/lua/5.1/https/init.lua'
no file './https.dll'
```

I respected the android compilation folder structure indicated in the lua-https wiki and used the last available version of love-android.

Am I missing something?

**Comment by lmfff** [comment]
Here it is:
```
> Configure project :love
3rd-party module: C:\Users\lmfff\Documents\LOVE2D\love-android\love\src\jni\lua-modules\lua-https
Registered path C:\Users\lmfff\Documents\LOVE2D\love-android\love\src\jni\lua-modules\lua-https/src/android/java
```

**Comment by MikuAuahDark** [comment]
Can you verify that the https.so is available inside the APK? Try to open the APK as Zip archive.

> This can be verified by checking the APK with Zip viewer application and inspecting files in `lib/arm64-v8a` and `lib/armeabi-v7a`.

**Comment by lmfff** [comment]
The files found in the APK `lib/arm64-v8a` and `lib/armeabi-v7a` are:

- `libc++_shared.so`
- `liblove.so`
- `libmpg123.so`
- `libopenal.so`

No sign of https.so

**Comment by MikuAuahDark** [comment]
How you compile the project? Try `gradlew clean` then do `gradlew <whatever your build flavor is> > buildlog.txt 2>&1` then upload buildlog.txt either privately in Discord DM or in here.

**Comment by lmfff** [comment]
Here's the buildlog genereted after excuting `gradlew clean` and then `gradlew assembleEmbedNoRecord > buildlog.txt 2>&1`
Let me know if there's anything else I can provide.
Thanks!
[buildlog.txt](https://github.com/love2d/lua-https/files/8596943/buildlog.txt)

**Comment by MikuAuahDark** [comment]
Alright one last thing. Do you have `Android.mk` in `love/src/jni/lua-modules`? That single `Android.mk` needs to be there.

Otherwise then I'll have to test it ASAP.

**Comment by lmfff** [comment]
Yes, the structure of my `love/src/jni/lua-modules` is:
- `lua-https`
- `Android.mk`
- `lua-modules-readme.txt`

**Comment by lmfff** [comment]
I just noticed that https://www.love2d.org/wiki/Game_Distribution says:
> Then, download the Android SDK (exactly API 31 for 11.4) and Android NDK (exactly version 21.3.6528147 or r21d for 11.4). 

While https://github.com/love2d/love-android/wiki/Building-L%C3%96VE-for-Android---Android-Studio says:

> Under SDK Platforms:
> 
> - Android 11.0 [API 30]
> 
> Under SDK Tools:
> 
> - Android SDK Platform-Tools
> - Android SDK Tools
> - Support Repository -> Android Support Repository
> - NDK, specifically version 21.3.6528147

Following the instructions of the second link instead of the first I have installed Android 11.0 [API 30] and NDK 21.3.6528147
Could this be causing the issue?
In that case how can I install NDK r21d ? I don't seem to find any version labeled like that in Android Studio.
![image](https://user-images.githubusercontent.com/25550975/166110476-b8846496-7b18-4269-aaa4-af85c02d1525.png)

**Comment by lmfff** [comment]
Updating to API 31 actually solved the issue!

**Comment by MikuAuahDark** [comment]
Updated love android wiki, thanks.
