### ISSUE TITLE
Support for `Accept-Encoding` and `Content-Encoding`?

### ISSUE THREAD

**Issue by nikneym** [love2d/lua-https#9]
By supporting mentioned headers, the response body can be received compressed. In general, this means reading less bytes and completing the request more performantly.

**Comment by MikuAuahDark** [comment]
Unfortunately you have to support this yourself in your HTTP code. lua-https does not care about content encoding and such. You have to send the `Accept-Encoding` header, check the `Content-Encoding` header, and decompress the response yourself.

For example, for gzip, you have to send `Accept-Encoding: gzip` then check if the `Content-Encoding` is `gzip`. If it's gzip, use `love.data.decompress` to decompress the response.
